import type { TaskDataType } from '../dataTypes/taskDataType';

export const mockData: TaskDataType[] = [
  {
    assignee: 'Jack Jones',
    description: 'Create AWS ec2 machine',
    name: 'AWS ec2 creation',
    reporter: 'Emily Ames',
    statusCode: 0,
    id: '1234',
  },
  {
    assignee: 'Sarah Connor',
    description: 'Deploy new website version',
    name: 'Website Deployment',
    reporter: 'Michael Smith',
    statusCode: 1,
    id: '1235',
  },
  {
    assignee: 'John Doe',
    description: 'Fix login bug',
    name: 'Login Bug Fix',
    reporter: 'Alice Johnson',
    statusCode: 2,
    id: '1236',
  },
  {
    assignee: 'Jane Doe',
    description: 'Update database schema',
    name: 'Database Schema Update',
    reporter: 'Robert Brown',
    statusCode: 0,
    id: '1237',
  },
  {
    assignee: 'Mark Lee',
    description: 'Design new landing page',
    name: 'Landing Page Design',
    reporter: 'Jessica Green',
    statusCode: 1,
    id: '1238',
  },
  {
    assignee: 'Emily White',
    description: 'Write unit tests for API',
    name: 'API Unit Tests',
    reporter: 'Paul Martinez',
    statusCode: 2,
    id: '1239',
  },
  {
    assignee: 'Daniel Kim',
    description: 'Create user authentication module',
    name: 'User Authentication',
    reporter: 'Laura Thomas',
    statusCode: 0,
    id: '1244',
  },
  {
    assignee: 'Olivia Wilson',
    description: 'Implement payment gateway',
    name: 'Payment Gateway',
    reporter: 'James Clark',
    statusCode: 1,
    id: '1245',
  },
  {
    assignee: 'Chris Evans',
    description: 'Optimize website performance',
    name: 'Performance Optimization',
    reporter: 'Emma Davis',
    statusCode: 2,
    id: '1246',
  },
  {
    assignee: 'Sophia Turner',
    description: 'Conduct security audit',
    name: 'Security Audit',
    reporter: 'David Harris',
    statusCode: 0,
    id: '1247',
  },
  {
    assignee: 'Liam Miller',
    description: 'Integrate third-party API',
    name: 'API Integration',
    reporter: 'Sophia Anderson',
    statusCode: 1,
    id: '1248',
  },
  {
    assignee: 'Isabella Lee',
    description: 'Refactor legacy code',
    name: 'Code Refactoring',
    reporter: 'Matthew Johnson',
    statusCode: 2,
    id: '1249',
  },
];
